# Generated by Django 2.2.1 on 2020-07-15 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='contact_no',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='s_name',
            new_name='name',
        ),
    ]
