# Generated by Django 2.2.1 on 2020-07-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200715_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_data',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=64)),
                ('contactno', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.IntegerField()),
            ],
        ),
    ]
