# Generated by Django 2.2.1 on 2020-07-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_student_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_data',
            name='password',
            field=models.CharField(max_length=64),
        ),
    ]
