# Generated by Django 2.2.1 on 2020-07-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200715_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enroll_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=64)),
                ('cname', models.CharField(max_length=50)),
                ('phno', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
